{
  Iterator resultsIter=actualResults.iterator();
  Iterator resultsIter2=actualResults.iterator();
  Iterator expectedResultsIter=expectedResults.iterator();
  while (resultsIter.hasNext() && resultsIter2.hasNext() && expectedResultsIter.hasNext()) {
    Object expectedNext=expectedResultsIter.next();
    final Object next=resultsIter.next();
    final Object next2=resultsIter2.next();
    Assert.assertEquals(failMsg,expectedNext,next);
    Assert.assertEquals(String.format("%sSecond iterator bad, multiple calls to iterator() should be safe",failMsg),expectedNext,next2);
  }
  if (resultsIter.hasNext()) {
    Assert.fail(String.format("%sExpected resultsIter to be exhausted, next element was %s",failMsg,resultsIter.next()));
  }
  if (resultsIter2.hasNext()) {
    Assert.fail(String.format("%sExpected resultsIter2 to be exhausted, next element was %s",failMsg,resultsIter.next()));
  }
  if (expectedResultsIter.hasNext()) {
    Assert.fail(String.format("%sExpected expectedResultsIter to be exhausted, next element was %s",failMsg,expectedResultsIter.next()));
  }
}
