{
  Exception ex=null;
  try {
    TestHelper.getTestIndexIO().validateTwoSegments(adapter1,adapter2);
  }
 catch (  Exception e) {
    ex=e;
  }
  if (exception != null) {
    Assert.assertNotNull("Exception was not thrown",ex);
    if (!exception.isAssignableFrom(ex.getClass())) {
      throw ex;
    }
  }
 else {
    if (ex != null) {
      throw ex;
    }
  }
}
